apps/images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create_image_set/', views.ImageSetCreateView.as_view(),
         name='imageset_create_url'),

    path('<int:pk>/update_image_set/', views.ImageSetUpdateView.as_view(),
         name='imageset_update_url'),

    path('image_set_list/', views.ImageSetListView.as_view(),
         name='imageset_list_url'),

    path('<int:pk>/imageset/', views.ImageSetDetailView.as_view(),
         name='imageset_detail_url'),

    path('<int:pk>/upload_images/', views.ImagesUploadView.as_view(),
         name='upload_images_url'),

    path('<int:pk>/images_list/', views.ImagesListView.as_view(),
         name='images_list_url'),

    path('<int:imgset_pk>/delete_image/<int:pk>/', views.ImagesDeleteUrl.as_view(),
         name='image_delete_url'),

     path('delete_imageset/<int:pk>/', views.ImagesetDeleteUrl.as_view(),
         name='imageset_delete_url'),
]

apps/videos/urls.py
from django.urls import path
from . import views

app_name = 'videos'

urlpatterns = [
    path('create_video_set/', views.VideoSetCreateView.as_view(),
         name='videoset_create_url'),

    path('<int:pk>/update_video_set/', views.VideoSetUpdateView.as_view(),
         name='videoset_update_url'),

    path('video_set_list/', views.VideoSetListView.as_view(),
         name='videoset_list_url'),

    path('<int:pk>/videoset/', views.VideoSetDetailView.as_view(),
         name='videoset_detail_url'),

    path('<int:pk>/upload_videos/', views.VideosUploadView.as_view(),
         name='upload_videos_url'),

    path('<int:pk>/videos_list/', views.VideosListView.as_view(),
         name='videos_list_url'),

    path('<int:imgset_pk>/delete_video/<int:pk>/', views.VideosDeleteUrl.as_view(),
         name='video_delete_url'),

     path('delete_videoset/<int:pk>/', views.VideosetDeleteUrl.as_view(),
         name='videoset_delete_url'),
]

apps/webcam/urls.py
from django.urls import path
from . import views

app_name = 'webcam'

urlpatterns = [
    path('stream/', views.video_feed, name='stream'),
]

btl/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from apps.images.views import HomeTemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('students.urls'), name="home_url"),
    path('test/', HomeTemplateView.as_view(), name="test_url"),
    path('', include('apps.images.urls')),
    path('', include('apps.detect.urls')),
    path('', include('apps.webcam.urls')),
    path('', include('apps.videos.urls')),
    path('', include('apps.user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.index, name='index'),
  path('timesheet/', views.view_timesheet, name='timesheet'),
  path('<int:id>', views.view_student, name='view_student'),
  path('add/', views.add, name='add'),
  path('edit/<int:id>/', views.edit, name='edit'),
  path('delete/<int:id>/', views.delete, name='delete'),
]

students/models.py
from django.db import models
import os

# Create your models here.
class Student(models.Model):
  student_number = models.PositiveIntegerField(null=True)
  image = models.ImageField(upload_to='images/',null=True)
  first_name = models.CharField(max_length=50, null=True)
  last_name = models.CharField(max_length=50, null=True)
  email = models.EmailField(max_length=100, null=True)
  field_of_study = models.CharField(max_length=50, null=True)
  gpa = models.FloatField(null=True)

  def __str__(self):
    return f'{self.image.path}'

  def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
  
# class TimesheetHistory(models.Model):
#   student_number = models.PositiveIntegerField()
#   lastChecked = models.

#   def __str__(self):
#     return f'Student: {self.first_name} {self.last_name}'

students/forms.py
from django import forms 
from .models import Student


class StudentForm(forms.ModelForm):
  class Meta:
    model = Student
    fields = ['student_number','image', 'first_name', 'last_name', 'email', 'field_of_study', 'gpa']
    labels = {
      'student_number': 'Student Number',
      'image': 'Student Image',
      'first_name': 'First Name', 
      'last_name': 'Last Name', 
      'email': 'Email', 
      'field_of_study': 'Field of Study', 
      'gpa': 'GPA'
    }
    widgets = {
      'student_number': forms.NumberInput(attrs={'class': 'form-control'}), 
      'image': forms.FileInput(attrs = {'class': 'form-control'}), 
      'first_name': forms.TextInput(attrs={'class': 'form-control'}),
      'last_name': forms.TextInput(attrs={'class': 'form-control'}),
      'email': forms.EmailInput(attrs={'class': 'form-control'}),
      'field_of_study': forms.TextInput(attrs={'class': 'form-control'}),
      'gpa': forms.NumberInput(attrs={'class': 'form-control'}),
    }

students/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Student
from .forms import StudentForm

# Create your views here.
def index(request):
  return render(request, 'students/index.html', {
    'students': Student.objects.all()
  })

def view_student(request, id):
  student = Student.objects.get(pk=id)
  return HttpResponseRedirect(reverse('index'))

def view_timesheet(request):
  return render(request, 'students/timesheet.html', {
        
      }) 

def add(request):
  if request.method == 'POST':
    form = StudentForm(request.POST, request.FILES)
    if form.is_valid():
      new_student_number = form.cleaned_data['student_number']
      new_student_image = form.cleaned_data["image"]
      new_first_name = form.cleaned_data['first_name']
      new_last_name = form.cleaned_data['last_name']
      new_email = form.cleaned_data['email']
      new_field_of_study = form.cleaned_data['field_of_study']
      new_gpa = form.cleaned_data['gpa']


      new_student = Student(
        student_number = new_student_number,
        image = new_student_image,
        first_name = new_first_name,
        last_name = new_last_name,
        email = new_email,
        field_of_study = new_field_of_study,
        gpa = new_gpa
      )
      new_student.save()
      return render(request, 'students/add.html', {
        'form': StudentForm(),
        'success': True
      })
  else:
    form = StudentForm()
  return render(request, 'students/add.html', {
    'form': StudentForm()
  })

def edit(request, id):
  if request.method == 'POST':
    student = Student.objects.get(pk=id)
    form = StudentForm(request.POST, instance=student)
    if form.is_valid():
      form.save()
      return render(request, 'students/edit.html', {
        'form': form,
        'success': True
      })
  else:
    student = Student.objects.get(pk=id)
    form = StudentForm(instance=student)
  return render(request, 'students/edit.html', {
    'form': form
  })

def delete(request, id):
  if request.method == 'POST':
    student = Student.objects.get(pk=id)
    student.delete()
  return HttpResponseRedirect(reverse('index'))

students/templates/students/add.html
{% extends "students/base.html" %}

{% block body %}
  <h3 class="text-center m-4">Add Student</h3>
  {% if success %}
    <div class="alert alert-success" role="alert">
      The new student added successfully.
      <a href="{% url 'index' %}" class="alert-link">Go to Home Page.</a>
    </div>
  {% else %}
    <div class="row justify-content-center">
      <div class="col-6">
        <div class="card bg-light mb-3">
          <div class="card-header">
            <i class="fa-solid fa-address-card fa-lg"></i> Student Registration
          </div>
          <div class="card-body">
            <form action="{% url 'add' %}" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Add</button>
              <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

students/templates/students/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Student Management System</title>
		<link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
		/>
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
	</head>
	<body class="d-flex flex-column min-vh-100">
		<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
			<div class="container-fluid">
				<a class="navbar-brand" href="{% url 'index' %}">
					<i class="fa-solid fa-graduation-cap fa-lg"></i> Student
					Management System
				</a>
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarColor01"
					aria-controls="navbarColor01"
					aria-expanded="false"
					aria-label="Toggle navigation"
				>
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarColor01">
					<ul class="navbar-nav me-auto">
						<li class="nav-item">
							<a class="nav-link" href="{% url 'index' %}">
								<i class="fa-solid fa-list fa-lg"></i> All
								Students
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'add' %}">
								<i class="fa-solid fa-plus fa-lg"></i> Add
								Student
							</a>
						</li>
						{% comment %} <li class="nav-item">
							<a class="nav-link" href="{% url 'timesheet' %}">
								<i class="fa-solid fa-plus fa-lg"></i> Timesheet
							</a>
						</li> {% endcomment %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'images:imageset_list_url' %}">
								<i class="fa-solid fa-plus fa-lg"></i> Image Management
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'videos:videoset_list_url' %}">
								<i class="fa-solid fa-plus fa-lg"></i> Video Management
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'webcam:stream' %}">
								<i class="fa-solid fa-plus fa-lg"></i> Checkin
							</a>
						</li>
					</ul>
				</div>
					<!-- {% for student in students %}
						<span>Welcome, {{ student.first_name }}</span>
					{%endfor%} -->
					<a class="btn btn-primary" style="position: relative; right:0; color:#fff" href="login/">Logout</a>
				</div>
			</div>
		</nav>
		<div class="container-fluid">{% block body %} {% endblock %}</div>
		<footer class="mt-auto mb-4">
			<div class="text-center">
				<span> </span>
			</div>
		</footer>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
	</body>
</html>

students/templates/students/edit.html
{% extends "students/base.html" %}

{% block body %}
  <h3 class="text-center m-4">Update Student</h3>
  {% if success %}
    <div class="alert alert-success" role="alert">
      The student updated successfully.
      <a href="{% url 'index' %}" class="alert-link">Go to Home Page.</a>
    </div>
  {% else %}
    <div class="row justify-content-center">
      <div class="col-6">
        <div class="card bg-light mb-3">
          <div class="card-header">
            <i class="fa-solid fa-pen-to-square fa-lg"></i> Update Student Records
          </div>
          <div class="card-body">
            <form action="" method="POST">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Update</button>
              <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

students/templates/students/index.html
{% extends "students/base.html" %}

{% block body %}
<h3 class="m-4">All Students</h3>
<div class="row">
  <div class="col-12">
    {% if students %}
    <div class="card bg-light ms-4 me-4 mb-4">
      <div class="card-header">
        <i class="fa-solid fa-list fa-lg"></i> Student Records
      </div>
      <div class="card-body">
        <p class="card-text">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Student Number</th>
                  <th scope="col">Student Image</th>
                  <th scope="col">First Name</th>
                  <th scope="col">Last Name</th>
                  <th scope="col">Email</th>
                  <th scope="col">Field of Study</th>
                  <th scope="col">GPA</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for student in students %}
                  <tr>
                    <td>{{ student.student_number }}</td>
                    <td><img style="width:64px; height:64px; object-fit: cover" src="{{ student.image.url }}"/></td>
                    <td>{{ student.first_name }}</td>
                    <td>{{ student.last_name }}</td>
                    <td>{{ student.email }}</td>
                    <td>{{ student.field_of_study }}</td>
                    <td>{{ student.gpa }}</td>
                    <td>
                      <button type="button" class="btn btn-success me-1" href="{% url 'view_student' student.id %}" data-bs-toggle="modal" data-bs-target="#myModal{{student.id}}">
                        <i class="fa-solid fa-circle-info fa-lg"></i>
                      </button>

                      <!-- Modal - View Student -->
                      <div class="modal" id="myModal{{student.id}}" tabindex="-1" aria-labelledby="myModalLabel1" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title">
                                Student: {{ student.first_name }} {{ student.last_name }}
                              </h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true"></span>
                              </button>
                            </div>
                            <div class="modal-body">
                              <ul class="list-unstyled">
                                <li>Student Number: <strong>{{ student.student_number }}</strong></li>
                                <li>First Name: <strong>{{ student.first_name }}</strong></li>
                                <li>Last Name: <strong>{{ student.last_name }}</strong></li>
                                <li>Email: <strong>{{ student.email }}</strong></li>
                                <li>Field of Study: <strong>{{ student.field_of_study }}</strong></li>
                                <li>GPA: <strong>{{ student.gpa }}</strong></li>
                              </ul>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                            </div>
                          </div>
                        </div>
                      </div>

                      <a class="btn btn-warning me-1" href="{% url 'edit' student.id %}">
                        <i class="fa-solid fa-pen-to-square fa-lg"></i>
                      </a>

                      <a class="btn btn-success me-1" href="{% url 'images:imageset_create_url'%}">
                        <i class="fa-solid fa-upload fa-lg"></i>
                      </a>

                      <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete{{student.id}}">
                        <i class="fa-solid fa-trash-can fa-lg"></i>
                      </button>

                      <!-- Modal - Delete Student -->
                      <div class="modal" id="delete{{student.id}}" tabindex="-1" aria-labelledby="myModalLabel2" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title">
                                Student: {{ student.first_name }} {{ student.last_name }}
                              </h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true"></span>
                              </button>
                            </div>
                            <div class="modal-body">
                              <p>Are you sure you want to delete this student?</p>
                            </div>
                            <div class="modal-footer">
                              <form action="{% url 'delete' student.id %}" method="POST">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-primary" value="Delete">
                              </form>
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </p>
      </div>
    </div>
    {% else %}
      <h5 class="alert alert-primary ms-4 me-4">No Student Records</h5>
    {% endif %}
  </div>
</div>
{% endblock %}

students/templates/students/timesheet.html
{% extends "students/base.html" %} 

{% comment %} {% extends 'base.html' %}  {% endcomment %}
{% comment %} {% block title %}
    Home Page
{% endblock title %} {% endcomment %}

{% block body %}
<div class="col-md-12 mt-2">
    <div class="card">
    <h4 class="card-header">Checkin Management</h4>
    <div class="card-body">
        {% comment %} <h5 class="card-title">Checkin Management</h5> {% endcomment %}

        <ul class="list-group list-group-flush">
            <li class="list-group-item">Upload Image: 
                <a href="{% url 'images:imageset_create_url' %}" class="btn btn-sm btn-outline-success" type="button">Create Imageset</a>
                <a href="{% url 'images:imageset_list_url' %}" class="btn btn-sm btn-outline-success" type="button">My ImageSets List</a>
            </li>
            </li>
        </ul>
       
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Upload Video: 
                <a href="{% url 'videos:videoset_create_url' %}" class="btn btn-sm btn-outline-success" type="button">Create Videoset</a>
                <a href="{% url 'videos:videoset_list_url' %}" class="btn btn-sm btn-outline-success" type="button">My VideoSets List</a>
            </li>
            </li>
        </ul>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Checkin: 
                <a href="{% url 'webcam:stream' %}" class="btn btn-sm btn-outline-success" type="button">Open Webcam</a>  
            </li>
            </li>
        </ul>
        
    </div>
    </div>
</div>  
{% endblock body %}