apps/detect/urls.py
from django.urls import path
from . import views

app_name = "detect"

urlpatterns = [
    path("<int:pk>/selected_image/",
         views.InferencedImageDetectionView.as_view(),
         name="detection_image_detail_url"
         ),
    path("<int:pk>/selected_video/",
         views.InferencedVideoDetectionView.as_view(),
         name="detection_video_detail_url"
         ),
]

apps/videos/urls.py
from django.urls import path
from . import views

app_name = 'videos'

urlpatterns = [
    path('create_video_set/', views.VideoSetCreateView.as_view(),
         name='videoset_create_url'),

    path('<int:pk>/update_video_set/', views.VideoSetUpdateView.as_view(),
         name='videoset_update_url'),

    path('video_set_list/', views.VideoSetListView.as_view(),
         name='videoset_list_url'),

    path('<int:pk>/videoset/', views.VideoSetDetailView.as_view(),
         name='videoset_detail_url'),

    path('<int:pk>/upload_videos/', views.VideosUploadView.as_view(),
         name='upload_videos_url'),

    path('<int:pk>/videos_list/', views.VideosListView.as_view(),
         name='videos_list_url'),

    path('<int:imgset_pk>/delete_video/<int:pk>/', views.VideosDeleteUrl.as_view(),
         name='video_delete_url'),

     path('delete_videoset/<int:pk>/', views.VideosetDeleteUrl.as_view(),
         name='videoset_delete_url'),
]

btl/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from apps.images.views import HomeTemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('students.urls'), name="home_url"),
    path('test/', HomeTemplateView.as_view(), name="test_url"),
    path('', include('apps.images.urls')),
    path('', include('apps.detect.urls')),
    path('', include('apps.webcam.urls')),
    path('', include('apps.videos.urls')),
    path('', include('apps.user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/videos/models.py
import os
from PIL import Image as I

from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

# Create your models here.
class VideoSet(models.Model):
    name = models.CharField(max_length=100,
                            help_text="eg. flowers"
                            )
    description = models.TextField()
    dirpath = models.CharField(max_length=150, null=True, blank=True)

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['name'],
            name='unique_videoset_by_user')]

    def __str__(self):
        return f'{self.name.capitalize()}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        print("save() called")
    save.alters_data = True

    def get_absolute_url(self):
        return reverse("videos:videoset_detail_url", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("videos:videoset_list_url", kwargs={})


def videoset_upload_videos_path(instance, filename):
    return f'{instance.video_set.dirpath}/videos/{filename}'

class VideoFile(models.Model):
    name = models.CharField(_('Video Name'), max_length=150, null=True)
    video_set = models.ForeignKey('videos.VideoSet',
                                  related_name="videos",
                                  on_delete=models.CASCADE,
                                  help_text="Video Set of the uploading videos"
                                  )
    video = models.FileField(upload_to=videoset_upload_videos_path)

    is_inferenced = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    @ property
    def get_videourl(self):
        return self.video.url

    @ property
    def get_videopath(self):
        return self.video.path

    @ property
    def get_filename(self):
        return os.path.split(self.video.url[-1])

    @ property
    def get_imgshape(self):
        im = I.open(self.get_videopath)
        return im.size

    def get_delete_url(self):
        return reverse("videos:videos_list_url", kwargs={"pk": self.video_set.id})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

apps/videos/forms.py
from django import forms
from .models import VideoFile

class VideosFileForm(forms.Form):
    class Meta:
        model = VideoFile
        fields = ['name','video']

apps/videos/views.py
import random
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
from PIL import Image as im
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView, TemplateView
from django.views.generic import View
from django.shortcuts import get_object_or_404, render
import subprocess

import cv2
import numpy as np

from .forms import VideosFileForm
from .models import VideoFile, VideoSet

# Create your views here.
class VideoSetCreateView(CreateView):
    model = VideoSet
    fields = ['name', 'description']

    def form_valid(self, form):
        if not VideoSet.objects.filter(name=form.instance.name).exists():
            return super().form_valid(form)
        else:
            form.add_error(
                'name',
                f"Videoset with name {form.cleaned_data['name']} already exists in dataset. \
                     Add more videos to that imageset, if required."
            )
            return HttpResponseRedirect(reverse('videos:videoset_create_url'))


class VideoSetUpdateView(UpdateView):
    model = VideoSet
    fields = ['name', 'description']

    def form_valid(self, form):
        if not VideoSet.objects.filter(name=form.instance.name).exists():
            return super().form_valid(form)
        else:
            print("entered in else")
            form.add_error(
                'name',
                f"Videoset with name {form.cleaned_data['name']} already exists in dataset. \
                     Add more videos to that videoset, if required."
            )
            context = {
                'form': form
            }
            return render(self.request, 'videos/videoset_form.html', context)

    def get_success_url(self):
        return reverse('videos:videoset_detail_url', kwargs={'pk': self.object.id})


class VideoSetListView(ListView):
    model = VideoSet
    context_object_name = 'videosets'


class VideoSetDetailView(DetailView):
    model = VideoSet
    context_object_name = 'videoset'


class VideosUploadView(View):
    
    # fields = ['name', 'video']

    def get(self, request, *args, **kwargs):
        videoset_id = self.kwargs.get("pk")
        videoset = get_object_or_404(VideoSet, id=videoset_id)
        context = {
            'videoset': videoset,
        }
        return render(request, 'videos/videofile_form.html', context)

    def post(self, request, *args, **kwargs):
        videoset_id = self.kwargs.get("pk")
        videoset = get_object_or_404(VideoSet, id=videoset_id)
        if self.request.method == 'POST':
            videos = self.request.FILES.get("file")

            for f in request.FILES.getlist('file'):
                print(f.name)
                video = VideoFile(name=f.name, video=f, video_set=videoset)
                video.save()

            message = f"Uploading videos to the Videoset: {videoset}. \
                Automatic redirect to the images list after completion."

            redirect_to = reverse_lazy(
                "videos:videos_list_url", args=[videoset_id])

            return redirect(redirect_to)

class VideosListView(ListView):
    model = VideoFile
    context_object_name = 'videos'
    
    def get_queryset(self):
        videoset_id = self.kwargs.get('pk')
        return super().get_queryset().filter(video_set__id=videoset_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        videoset_id = self.kwargs.get('pk')
        videoset = get_object_or_404(VideoSet, id=videoset_id)
        context["videoset"] = videoset
        return context

class VideosDeleteUrl(DeleteView):
    model = VideoFile

    def get_success_url(self):
        qs = self.get_object()
        return qs.get_delete_url()

class VideosetDeleteUrl(DeleteView):
    model = VideoSet

    def get_success_url(self):
        qs = self.get_object()
        return qs.get_delete_url()

apps/videos/templates/videos/videofile_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="col-md-8 mt-2">
	<form action="" method="post">
		{% csrf_token %}
		<div class="alert alert-danger" role="alert">
			Bạn có chắc muốn xóa video này không?
		</div>
		<input type="submit" value="Xóa" class="btn btn-outline-danger" />
	</form>
</div>
{% endblock content %}

apps/videos/templates/videos/videofile_form.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %} 
{% block on_page_css %}
<link
	rel="stylesheet"
	type="text/css"
	href="{% static 'css/basic.min.css' %}"
/>
<link
	rel="stylesheet"
	type="text/css"
	href="{% static 'css/dropzone.min.css' %}"
/>
{% endblock on_page_css %} 
{% block title %} {{videoset.name|capfirst}} - Videos upload {% endblock title %} 
{% block content %}

<div class="col-md-11 mx-4">
	<h4 class="mb-4">
		Upload videos to {{ videoset.name|capfirst }} video set.
	</h4>
	<form
		action="{% url 'videos:upload_videos_url' videoset.id %}"
		method="post"
		enctype="multipart/form-data"
	>
		{% csrf_token %}
		<input name="file" type="file" />
		<button id="imagesUploadBtn" type="submit" class="btn btn-sm btn-outline-info mt-2" >
			Submit
		</button>
	</form>
	<!-- <form action="/file-upload" class="dropzone">
            <div class="fallback">
              <input name="file" type="file" multiple />
            </div>
        </form> -->
	<a class="btn btn-primary" style="width:200px" href="{% url 'videos:videos_list_url' videoset.id %}">Go Video List</a>
</div>
{% endblock content %} 
{% block on_page_js %}
<!-- <script src="{% static 'js/dropzone.min.js' %}"></script> -->
<!-- <script src="{% static 'js/custom.js' %}"></script> -->

{% endblock on_page_js %}

apps/videos/templates/videos/videofile_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .video-card {
        width: 320px;
        height: 240px;
        display: flex;
        flex-direction: row;
    }
</style>
<div class="container">
    <div class="row">
        {% for video in videos %}
        {% with video.get_videourl as videourl %}
        <div class="col">
            <video class="video-card card-image-top" controls>
                <source src="{{videourl}}" type="video/mp4"></source>
            </video>
            
            <a href="{% url 'videos:video_delete_url' video.video_set.id video.id %}" class="btn btn-sm btn-outline-success mx-1 my-1">
                <img src="{% static 'img/cross.png' %}" alt="" />
            </a>
            <a href="{% url 'detect:detection_video_detail_url' video.id %}" class="btn btn-sm btn-outline-success mx-1 my-1">
                Detect Objects
            </a>
        </div>
        {% endwith %}
        {% endfor %}
    </div>
    
</div>
{% endblock content %}

apps/videos/templates/videos/videoset_confirm_delete.html
{% extends 'base.html' %}
{% load static %} 

{% block content %}
<div class="col-md-8 mt-2">
	<form action="" method="post">
		{% csrf_token %}
		<div class="alert alert-danger" role="alert">
			Bạn có chắc muốn xóa tệp video này không?
		</div>
		<input type="submit" value="Xóa" class="btn btn-outline-danger" />
	</form>
</div>
{% endblock content %}

apps/videos/templates/videos/videoset_detail.html
{% extends 'base.html' %}
{% block title %} 
	{{ videoset.name }} - ImageSet 
{% endblock title %} 
{% block content %}
<div class="col-md-10 mx-4">
	<div class="card">
		<div class="card-header">{{ videoset.name|capfirst }} - Video set</div>
		<div class="card-body">
			<ul class="list-group list-group-flush">
				<li class="list-group-item">
					<b>Uploaded by</b>: {{ videoset.user|capfirst }}
				</li>
				<li class="list-group-item">
					<b>Total videos</b>: {{ videoset.videos.count }}
				</li>
				<li class="list-group-item">
					<b>Description</b>: {{ videoset.description }}
				</li>
			</ul>
			<a
				href="{% url 'videos:upload_videos_url' videoset.id %}"
				class="btn btn-outline-info btn-sm"
				>Upload videos</a
			>
			<a
				href="{% url 'videos:videoset_update_url' videoset.id %}"
				class="btn btn-outline-info btn-sm"
				>Update VideoSet</a
			>
			<a
				href="{% url 'videos:videoset_delete_url' videoset.id %}"
				class="btn btn-outline-info btn-sm"
				>Delete VideoSet</a
			>
			{% if videoset.videos.count > 0 %}
			<a
				href="{% url 'videos:videos_list_url' videoset.id %}"
				class="btn btn-outline-info btn-sm"
				>View Videos</a
			>
			{% endif %}
		</div>
	</div>
</div>
{% endblock content %} 
{% block shared_data %} 
	{{orig_video.id|json_script:"videoId" }} 
{% endblock shared_data %}

apps/videos/templates/videos/videoset_form.html
{% extends 'base.html' %}  
{% load static crispy_forms_tags %} 

{% block title %}
	Create videos set 
{% endblock title %} 
{% block content %}
<div class="col-md-7">
	<legend class="border-bottom">
		{% if 'update' in request.path %} 
			Update 
		{% else %} 
			Create 
		{% endif %}
			Video Set
	</legend>
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %} {{ form|crispy }}
		<button type="submit" class="btn btn-sm btn-outline-info mt-2">
			{% if 'update' in request.path %} 
				Update 
			{% else %} 
				Create 
			{% endif %}
		</button>
	</form>
	<a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary">Back</a>
</div>
{% endblock content %}

apps/videos/templates/videos/videoset_list.html
{% extends 'base.html' %} 
{% load static crispy_forms_tags %} 
{% block content %}
<div class="container">
	<div class="row mb-3">
		<a
			class="btn btn-sm btn-outline-success mx-1"
			type="button"
			href="{% url 'videos:videoset_create_url' %}"
			>Create videoset</a
		>
	</div>
	<div class="row">
		{% if object_list is None %}
		<h1>None</h1>
		{% else %} {% for videoset in object_list %}
		<div class="card mb-3">
			<div class="card-header">
				<a href="{% url 'videos:videoset_detail_url' videoset.id %}"
					>{{ videoset }}</a
				>
			</div>
			<div class="card-body">
				<ul class="list-group list-group-flush">
					<li class="list-group-item">
						<b>Uploaded by</b>: {{ videoset.user|capfirst }}
					</li>
					<li class="list-group-item">
						<b>Total videos</b>: {{ videoset.videos.count }}
					</li>
				</ul>
			</div>
		</div>
		{% endfor %} {% endif %}
	</div>
</div>
{% endblock content %}