apps/detect/urls.py
from django.urls import path
from . import views

app_name = "detect"

urlpatterns = [
    path("<int:pk>/selected_image/",
         views.InferencedImageDetectionView.as_view(),
         name="detection_image_detail_url"
         ),
    path("<int:pk>/selected_video/",
         views.InferencedVideoDetectionView.as_view(),
         name="detection_video_detail_url"
         ),
]

apps/images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create_image_set/', views.ImageSetCreateView.as_view(),
         name='imageset_create_url'),

    path('<int:pk>/update_image_set/', views.ImageSetUpdateView.as_view(),
         name='imageset_update_url'),

    path('image_set_list/', views.ImageSetListView.as_view(),
         name='imageset_list_url'),

    path('<int:pk>/imageset/', views.ImageSetDetailView.as_view(),
         name='imageset_detail_url'),

    path('<int:pk>/upload_images/', views.ImagesUploadView.as_view(),
         name='upload_images_url'),

    path('<int:pk>/images_list/', views.ImagesListView.as_view(),
         name='images_list_url'),

    path('<int:imgset_pk>/delete_image/<int:pk>/', views.ImagesDeleteUrl.as_view(),
         name='image_delete_url'),

     path('delete_imageset/<int:pk>/', views.ImagesetDeleteUrl.as_view(),
         name='imageset_delete_url'),
]

apps/videos/urls.py
from django.urls import path
from . import views

app_name = 'videos'

urlpatterns = [
    path('create_video_set/', views.VideoSetCreateView.as_view(),
         name='videoset_create_url'),

    path('<int:pk>/update_video_set/', views.VideoSetUpdateView.as_view(),
         name='videoset_update_url'),

    path('video_set_list/', views.VideoSetListView.as_view(),
         name='videoset_list_url'),

    path('<int:pk>/videoset/', views.VideoSetDetailView.as_view(),
         name='videoset_detail_url'),

    path('<int:pk>/upload_videos/', views.VideosUploadView.as_view(),
         name='upload_videos_url'),

    path('<int:pk>/videos_list/', views.VideosListView.as_view(),
         name='videos_list_url'),

    path('<int:imgset_pk>/delete_video/<int:pk>/', views.VideosDeleteUrl.as_view(),
         name='video_delete_url'),

     path('delete_videoset/<int:pk>/', views.VideosetDeleteUrl.as_view(),
         name='videoset_delete_url'),
]

apps/webcam/urls.py
from django.urls import path
from . import views

app_name = 'webcam'

urlpatterns = [
    path('stream/', views.video_feed, name='stream'),
]

btl/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from apps.images.views import HomeTemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('students.urls'), name="home_url"),
    path('test/', HomeTemplateView.as_view(), name="test_url"),
    path('', include('apps.images.urls')),
    path('', include('apps.detect.urls')),
    path('', include('apps.webcam.urls')),
    path('', include('apps.videos.urls')),
    path('', include('apps.user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/images/models.py
import os
from PIL import Image as I

from django.db import models
from django.conf import settings
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _

# Create your models here.
class ImageSet(models.Model):
    name = models.CharField(max_length=100,
                            help_text="eg. flowers"
                            )
    description = models.TextField()
    dirpath = models.CharField(max_length=150, null=True, blank=True)

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['name'],
            name='unique_imageset_by_user')]

    def __str__(self):
        return f'{self.name.capitalize()}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        print("save() called")
    save.alters_data = True

    def get_delete_url(self):
        return reverse("images:imageset_list_url", kwargs={})

    # def get_dirpath(self):
    #     rootdir = os.path.join(self.user.username, self.name)
    #     return rootdir

    def get_absolute_url(self):
        return reverse("images:imageset_detail_url", kwargs={"pk": self.pk})


def imageset_upload_images_path(instance, filename):
    return f'{instance.image_set.dirpath}/images/{filename}'

class ImageFile(models.Model):
    name = models.CharField(_('Image Name'), max_length=150, null=True)
    image_set = models.ForeignKey('images.ImageSet',
                                  related_name="images",
                                  on_delete=models.CASCADE,
                                  help_text="Image Set of the uploading images"
                                  )
    image = models.ImageField(upload_to=imageset_upload_images_path)

    is_inferenced = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    @ property
    def get_imageurl(self):
        return self.image.url

    @ property
    def get_imagepath(self):
        return self.image.path

    @ property
    def get_filename(self):
        return os.path.split(self.image.url[-1])

    @ property
    def get_imgshape(self):
        im = I.open(self.get_imagepath)
        return im.size

    def get_delete_url(self):
        return reverse("images:images_list_url", kwargs={"pk": self.image_set.id})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = I.open(self.get_imagepath)
        if img.height >= 640 and img.width >= 640:
            output_size = (640, 640)
            img.thumbnail(output_size)
            img.save(self.get_imagepath)
        else:
            print("ảnh lỗi rồi bạn ơi")

apps/images/views.py
import random
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
from PIL import Image as im
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView, TemplateView
from django.views.generic import View
from django.shortcuts import get_object_or_404, render

from .models import ImageFile, ImageSet

# Create your views here.
class HomeTemplateView(TemplateView):
    template_name = "images/mainview.html"

class ImageSetCreateView(CreateView):
    model = ImageSet
    fields = ['name', 'description']

    def form_valid(self, form):
        if not ImageSet.objects.filter(name=form.instance.name).exists():
            return super().form_valid(form)
        else:
            form.add_error(
                'name',
                f"Imageset with name {form.cleaned_data['name']} already exists in dataset. \
                     Add more images to that imageset, if required."
            )
            return HttpResponseRedirect(reverse('images:imageset_create_url'))


class ImageSetUpdateView(UpdateView):
    model = ImageSet
    fields = ['name', 'description']

    def form_valid(self, form):
        if not ImageSet.objects.filter(name=form.instance.name).exists():
            return super().form_valid(form)
        else:
            print("entered in else")
            form.add_error(
                'name',
                f"Imageset with name {form.cleaned_data['name']} already exists in dataset. \
                     Add more images to that imageset, if required."
            )
            context = {
                'form': form
            }
            return render(self.request, 'images/imageset_form.html', context)

    def get_success_url(self):
        return reverse('images:imageset_detail_url', kwargs={'pk': self.object.id})


class ImageSetListView(ListView):
    model = ImageSet
    context_object_name = 'imagesets'

    # def get_queryset(self):
    #     return super().get_queryset()

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["user_imagesets"] = ImageSet.objects.all()
    #     print(context)
    #     return context


class ImageSetDetailView(DetailView):
    model = ImageSet
    context_object_name = 'imageset'


class ImagesUploadView(View):
    def get(self, request, *args, **kwargs):
        imageset_id = self.kwargs.get("pk")
        imageset = get_object_or_404(ImageSet, id=imageset_id)
        context = {
            'imageset': imageset,
        }
        return render(request, 'images/imagefile_form.html', context)

    def post(self, request, *args, **kwargs):
        imageset_id = self.kwargs.get("pk")
        imageset = get_object_or_404(ImageSet, id=imageset_id)
        if self.request.method == 'POST':
            images = [self.request.FILES.get("file[%d]" % i)
                      for i in range(0, len(self.request.FILES))]
                        
            for f in request.FILES.getlist('file'):
                image = ImageFile(name=f.name, image=f, image_set=imageset)
                image.save()

            # for img in images:
                
            #     if not ImageFile.objects.filter(name=img.name, image_set=imageset).exists():
            #         ImageFile.objects.create(
            #             name=img.name, image=img, image_set=imageset)

            #     else:
            #         print(f"Image {img.name} already exists in the imageset.")

            message = f"Uploading images to the Imageset: {imageset}. \
                Automatic redirect to the images list after completion."

            redirect_to = reverse_lazy(
                "images:images_list_url", args=[imageset.id])
            return JsonResponse({"result": "result",
                                "message": message,
                                 "redirect_to": redirect_to,
                                 "files_length": len(images),
                                 },
                                status=200,
                                content_type="application/json"
                                )


class ImagesListView(ListView):
    model = ImageFile
    context_object_name = 'images'

    def get_queryset(self):
        imageset_id = self.kwargs.get('pk')
        return super().get_queryset().filter(image_set__id=imageset_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        imageset_id = self.kwargs.get('pk')
        imageset = get_object_or_404(ImageSet, id=imageset_id)
        context["imageset"] = imageset
        return context


class ImagesDeleteUrl(DeleteView):
    model = ImageFile

    def get_success_url(self):
        qs = self.get_object()
        return qs.get_delete_url()

class ImagesetDeleteUrl(DeleteView):
    model = ImageSet

    def get_success_url(self):
        qs = self.get_object()
        print(qs)
        return qs.get_delete_url()

apps/images/templates/images/imagefile_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="col-md-8 mt-2">
    <form action="" method="post">
    {% csrf_token %}
      <div class="alert alert-danger" role="alert">
      Bạn có chắc muốn xóa ảnh này không?
      </div>
    <input type="submit" value="Xóa" class="btn btn-outline-danger">
  </form>
</div>
{% endblock content %}

apps/images/templates/images/imagefile_form.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}

{% block on_page_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/basic.min.css' %}" > 
  <link rel="stylesheet" type="text/css" href="{% static 'css/dropzone.min.css' %}" />
{% endblock on_page_css %}

{% block title %}
{{imageset.name|capfirst}} - Images upload
{% endblock title %}


{% block content %}
    <div class="col-md-11 mx-4">
        <h4 class="mb-4">Upload images to {{ imageset.name|capfirst }} image set.</h4>
        <form action="{% url 'images:upload_images_url' imageset.id %}" method="post" enctype="multipart/form-data" class="dropzone dz" id="DzImageImport" >
            {% csrf_token %}
            <div class="dz-default dz-message upload_client">
                Drag & Drop Image files here {{imageset.id}} or <strong>click here</strong> to upload.
            </div>
        </form>
        <!-- <button id="imagesUploadBtn" type="submit" class="btn btn-sm btn-outline-info mt-2">Submit</button> -->
        <a class="btn btn-primary mt-2" style="width: 200px;" href="{% url 'images:images_list_url' imageset.id %}">Go Image List</a>
    </div>
{% endblock content %}

{% block on_page_js %}
<script src="{% static 'js/dropzone.min.js' %}"></script>
<!-- <script src="{% static 'js/custom.js' %}"></script> -->

{% endblock on_page_js %}

apps/images/templates/images/imagefile_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Multiple images list
{% endblock title %}

{% block content %}
<div class="col-md-9 mt-2">
    <div class="row">
        {% for image in images %}
        {% with image.get_imageurl as imgurl %}
        <div class="col-sm-3">
            <a href="{{ imgurl }}" data-toggle="lightbox" data-gallery="image-gallery">
                <img src="{{ imgurl }}" alt="" class="img-fluid mx-1 my-1" width="250px" height="250px" />
            </a>
            <a href="{% url 'images:image_delete_url' image.image_set.id image.id %}" class="btn btn-sm btn-outline-success mx-1 my-1">
                <img src="{% static 'img/cross.png' %}" alt="" />
            </a>
            <a href="{% url 'detect:detection_image_detail_url' image.id %}" class="btn btn-sm btn-outline-success mx-1 my-1">
                Detect Objects
            </a>
        </div>
        {% endwith %}
        {% endfor %}
    </div>
    
</div>
{% endblock content %}

apps/images/templates/images/imageset_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="col-md-8 mt-2">
    <form action="" method="post">
    {% csrf_token %}
      <div class="alert alert-danger" role="alert">
      Bạn có chắc muốn xóa tệp ảnh này không?
      </div>
    <input type="submit" value="Xóa" class="btn btn-outline-danger">
  </form>
</div>
{% endblock content %}

apps/images/templates/images/imageset_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ imageset.name }} - ImageSet
{% endblock title %}

{% block content %}
<div class="col-md-10 mx-4">
    <div class="card">
    <div class="card-header">
        {{ imageset.name|capfirst }} - Image set
    </div>
    <div class="card-body">
       <ul class="list-group list-group-flush">
            <li class="list-group-item"><b>Uploaded by</b>: {{ imageset.user|capfirst }}</li>
            <li class="list-group-item"><b>Total images</b>: {{ imageset.images.count }}</li>
            <li class="list-group-item"><b>Description</b>: {{ imageset.description }}</li>
        </ul>
            <a href="{% url 'images:upload_images_url' imageset.id %}" class="btn btn-outline-info btn-sm">Upload images</a>
            <a href="{% url 'images:imageset_update_url' imageset.id %}" class="btn btn-outline-info btn-sm">Update ImageSet</a>
            <a href="{% url 'images:imageset_delete_url' imageset.id %}" class="btn btn-outline-info btn-sm">Delete ImageSet</a>
            {% if imageset.images.count > 0 %}
                <a href="{% url 'images:images_list_url' imageset.id %}" class="btn btn-outline-info btn-sm">View Images</a>
            {% endif %}
    </div>
    </div>    
</div>
{% endblock content %}

{% block shared_data %}
    {{ orig_image.id|json_script:"imageId" }}
{% endblock shared_data %}

apps/images/templates/images/imageset_form.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}

{% block title %}
Create images set
{% endblock title %}

{% block content %}
    <div class="col-md-7">
        <legend class="border-bottom">
        {% if 'update' in request.path %}
            Update
        {% else %}
            Create
        {% endif %}
            Image Set
        </legend>
        <form action="" method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-sm btn-outline-info mt-2">
            {% if 'update' in request.path %}
                Update
            {% else %}
                Create
            {% endif %}
            </button>
        </form>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary" class>Back</a>
    </div>
{% endblock content %}

apps/images/templates/images/imageset_list.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}


{% block content %}
<div class="container">
    <div class="row mb-3">
        <a class="btn btn-sm btn-outline-success mx-1" type="button" href="{% url 'images:imageset_create_url' %}">Create imageset</a>
    </div>
    <div class="row">
        {% if object_list is None %}
            <h1>None</h1>
        {% else %}
            {% for imgset in object_list %}
            <div class="card mb-3">
                <div class="card-header">
                    <a href="{% url 'images:imageset_detail_url' imgset.id %}">{{ imgset }}</a>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><b>Uploaded by</b>: {{ imgset.user|capfirst }}</li>
                        <li class="list-group-item"><b>Total images</b>: {{ imgset.images.count }}</li>
                    </ul>
                </div>
            </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock content %}

apps/images/templates/images/mainview.html
{% extends 'base.html' %}

{% block title %}
    Home Page
{% endblock title %}

{% block content %}
<div class="col-md-12 mt-2">
    <div class="card">
    <h4 class="card-header">Face Detection With YoloV5</h4>
    <div class="card-body">
        <h5 class="card-title">Checkin Management</h5>

        <ul class="list-group list-group-flush">
            <li class="list-group-item">Upload Image: 
                <a href="{% url 'images:imageset_create_url' %}" class="btn btn-sm btn-outline-success" type="button">Create Imageset</a>
                <a href="{% url 'images:imageset_list_url' %}" class="btn btn-sm btn-outline-success" type="button">My ImageSets List</a>
            </li>
            </li>
        </ul>
       
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Upload Video: 
                <a href="{% url 'videos:videoset_create_url' %}" class="btn btn-sm btn-outline-success" type="button">Create Videoset</a>
                <a href="{% url 'videos:videoset_list_url' %}" class="btn btn-sm btn-outline-success" type="button">My VideoSets List</a>
            </li>
            </li>
        </ul>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Checkin: 
                <a href="{% url 'webcam:stream' %}" class="btn btn-sm btn-outline-success" type="button">Open Webcam</a>  
            </li>
            </li>
        </ul>
        
    </div>
    </div>
</div>  
{% endblock content %}