apps/user/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.index_login,
         name='index_login'),
    path('video_login/', views.video_login,
         name='video_login'),
    path('handle_login/', views.handle_login,
         name='handle_login'),
    path('register/', views.register_new_user,
         name='register'),
         
]

btl/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from apps.images.views import HomeTemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('students.urls'), name="home_url"),
    path('test/', HomeTemplateView.as_view(), name="test_url"),
    path('', include('apps.images.urls')),
    path('', include('apps.detect.urls')),
    path('', include('apps.webcam.urls')),
    path('', include('apps.videos.urls')),
    path('', include('apps.user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/user/models.py
from django.db import models

# Create your models here.

apps/user/forms.py
from django import forms

class NameForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)

apps/user/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.http import StreamingHttpResponse, HttpResponse, HttpResponseRedirect
import os.path
from tkinter import *
import subprocess
from .forms import NameForm
import cv2
from students.models import Student
from pathlib import Path

def index_login(request):
    return render (request, "user/login.html")


def add_webcam():
    global frame
    key = cv2. waitKey(1)
    cap = cv2.VideoCapture(0)
    
    while True:
        try:
            check, frame = cap.read()
            image_bytes = cv2.imencode('.jpg', frame)[1].tobytes()

            yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + image_bytes + b'\r\n')
    
        except(KeyboardInterrupt):
            print("Turning off camera.")
            cap.release()
            print("Camera off.")
            print("Program ended.")
            cv2.destroyAllWindows()
            break
       

def video_login(request):
    return StreamingHttpResponse(add_webcam(), content_type='multipart/x-mixed-replace; boundary=frame')   

students = Student.objects.all()
print(students)

path_parent = Path(f'{students[0]}')

db_dir = path_parent.parent.absolute()
unknown_img_path = './.tmp.jpg'
path = f'{db_dir}\./.tmp.jpg'

db = f'{db_dir}'


def handle_login(request):
    cv2.imwrite(unknown_img_path,frame)
    output = str(subprocess.check_output(['face_recognition', db, unknown_img_path]))
    name = output.split(',')[1][:-5]
    print(output)
    print(name)
    


    if name in ['unknown_person', 'no_persons_found']:
        os.remove(unknown_img_path)
        return render(request, "user/message.html")
    else:
        os.remove(unknown_img_path)
        return HttpResponseRedirect("/")

    

def register_new_user(request):

    if request.method == 'POST':
    # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            name = form['name'].value()
            path1 = f'{db_dir}\{name}.jpg'
            cv2.imwrite(path1,frame)
            student = Student(first_name=name, image=path1)
            student.save()
               
            
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/login')

        # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'user/register.html', {'form': form})

apps/user/templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
		/>
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <title>Users</title>
</head>

<body class="d-flex flex-column min-vh-100 w-full">
    <div class="container">
        <h1 class="mx-auto text-center">Đăng nhập</h1>
        <div class="d-flex justify-content-center">
            <img src="{% url 'login:video_login' %}" alt=""/>
        </div>
    </div>
    <div class="d-flex justify-content-center mt-2">
        <a class="btn btn-primary" href="{% url 'login:handle_login' %}">Login</a>
        <a class="btn btn-primary" style="margin-left:10px" href="{% url 'login:register' %}">Register new user</a>    
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

apps/user/templates/user/message.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="col-md-8 mt-2">
    <div class="alert alert-danger  m-2" role="alert">
        Lỗi
    </div>
    <button class="btn">
        <a href="/login" alt="">Go Back</a>
    </button>
</div>
{% endblock content %}

apps/user/templates/user/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
		/>
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <title>Users</title>
</head>

<body class="d-flex flex-column min-vh-100 w-full">
    <div class="container">
        <h1 class="mx-auto text-center">Đăng ký</h1>
        <div class="d-flex justify-content-center">
            <img src="{% url 'login:video_login' %}" alt=""/>
        </div>
    </div>
    <form method="post" class="mx-auto mt-2 d-flex justify-content-center">
        {% csrf_token %}
        <!-- <label for="your_name">Your name: </label>
        <input id="your_name" type="text" name="your_name" value=""> -->
        {{form.as_p}}
        <button class="btn btn-primary" style="margin-left:10px; height: 30px; padding: 0 10px;" type="submit" value="Submit">Submit</button>
    </form>
    <!-- <div class="d-flex justify-content-center mt-2">
        <a class="btn btn-primary" href="{% url 'login:handle_login' %}">Login</a>
    </div> -->
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>